INSERT INTO narrative_templates (name, direction, strength, leader, template_text, priority) VALUES
('post_market_opening', 'up', 'strong', 'nifty', 'Nifty roared ahead, closing the day up {nifty_pct}.', 2),
('post_market_opening', 'up', 'strong', 'sensex', 'Sensex powered higher with a standout {sensex_pct} jump.', 2),
('post_market_opening', 'up', 'strong', 'banknifty', 'Bank Nifty led the charge, finishing {banknifty_pct} stronger.', 2),
('post_market_opening', 'up', 'solid', 'nifty', 'Broad strength with Nifty in front at {nifty_pct}.', 1),
('post_market_opening', 'up', 'solid', 'sensex', 'Sensex set the tone, ending {sensex_pct} higher.', 1),
('post_market_opening', 'up', 'solid', 'banknifty', 'Financials steadied the advance as Bank Nifty closed {banknifty_pct}.', 1),
('post_market_opening', 'up', 'mild', 'any', 'Green finish with gains led by {leader_name}.', 0),
('post_market_opening', 'up', 'any', 'nifty', 'Nifty topped the scoreboard with a {nifty_pct} move.', 0),
('post_market_opening', 'up', 'any', 'sensex', 'Sensex was today’s anchor, up {sensex_pct}.', 0),
('post_market_opening', 'up', 'any', 'banknifty', 'Bank Nifty held the spotlight, closing {banknifty_pct}.', 0),
('post_market_opening', 'down', 'strong', 'nifty', 'Nifty sank sharply, sliding {nifty_pct} by the close.', 2),
('post_market_opening', 'down', 'strong', 'sensex', 'Sensex bore the brunt with a {sensex_pct} drop.', 2),
('post_market_opening', 'down', 'strong', 'banknifty', 'Bank Nifty tumbled hardest, finishing {banknifty_pct}.', 2),
('post_market_opening', 'down', 'solid', 'any', 'Red close with sellers leaning on {leader_name}.', 1),
('post_market_opening', 'down', 'mild', 'any', 'Softer close as {leader_name} drifted lower.', 0),
('post_market_opening', 'down', 'any', 'nifty', 'Nifty lagged peers, easing {nifty_pct}.', 0),
('post_market_opening', 'down', 'any', 'sensex', 'Sensex slipped {sensex_pct} to finish in the red.', 0),
('post_market_opening', 'down', 'any', 'banknifty', 'Bank Nifty retreated {banknifty_pct} at the bell.', 0),
('post_market_opening', 'mixed', 'any', 'nifty', 'Splintered tape with Nifty steering the day at {nifty_pct}.', 0),
('post_market_opening', 'mixed', 'any', 'sensex', 'Sensex was the steady hand amid a mixed close ({sensex_pct}).', 0),
('post_market_opening', 'mixed', 'any', 'banknifty', 'Bank Nifty swung widest as the market finished mixed ({banknifty_pct}).', 0),
('post_market_opening', 'mixed', 'solid', 'any', 'Cross-currents prevailed; {leader_name} held relative strength.', 1),
('post_market_opening', 'flat', 'any', 'any', 'Flat finish with little separation among the majors.', 0),
('post_market_opening', 'flat', 'mild', 'any', 'Sideways close; {leader_name} barely budged.', 0),
('post_market_opening', 'flat', 'solid', 'any', 'Tight range day; traders marked time into the close.', 0),
('post_market_opening', 'mixed', 'strong', 'any', 'Volatile swings ended mixed with {leader_name} dominating moves.', 1),
('post_market_opening', 'down', 'strong', 'any', 'Selling pressure broadened as {leader_name} led declines.', 1),
('post_market_opening', 'up', 'strong', 'any', 'Strong finish across the board with leadership from {leader_name}.', 1);
